--- #YAML:1.0
name:               Image-JpegTran
version:            0.02
abstract:           XS wrapper around lossless JPEG transformation utility - jpegtran
author:
    - Mons Anderson <mons@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
